services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: cydog
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: cydog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cydog -d cydog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DB_HOST=postgres
      - DB_USER=cydog
      - DB_PASSWORD=password123
      - DB_NAME=cydog_db
      - DB_PORT=5432
      - JWT_SECRET=your_jwt_secret_key
      - SESSION_SECRET=your_session_secret
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  postgres_data:
